FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir torch torchvision \
    kagglehub scikit-learn matplotlib seaborn pillow numpy

COPY chest_xray_pneumonia.py .

# Model will be saved to this volume
RUN mkdir -p /app/models

CMD ["python", "chest_xray_pneumonia.py"]
